version: '3.9'
# Local development stack — no AWS, no Aiven needed
# Usage: docker-compose -f docker-compose.local.yml up

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER:     qwikbrew
      POSTGRES_PASSWORD: qwikbrew
    ports: ["5432:5432"]
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts/init-dbs.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on: [zookeeper]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports: ["9092:9092"]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  service-discovery:
    build: ./service-discovery
    ports: ["8761:8761"]
    depends_on: [postgres]

volumes:
  pg_data:
